DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS customerData;
DROP TABLE IF EXISTS transactionData;
CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL,
    merchantID TEXT NOT NULL,
    apiKey TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);
